#!/bin/sh

./configure \
    --disable-static \
    --enable-shared \
    --enable-gtk-doc=no \
    --enable-xlib=no \
    --enable-xlib-xrender=no \
    --enable-xcb=no \
    --enable-qt=no \
    --enable-fc=yes \
    --enable-minigui=yes \
    --enable-gl=no \
    --enable-glesv2=no \
    --enable-glesv3=no \
    --enable-egl=no \
    --enable-glx=no \
    --enable-drm=no
